### ISSUE TITLE
Ошибка в переводе

### ISSUE THREAD

**Issue by demimurych** [iliakan/es5#11]
https://es5.javascript.ru/x8.html#x8

Неправильно:
Языковые типы соответствуют значениям, которыми непосредственно манипулирует создатель кода на языке ECMAScript. **К типам спецификации относятся**: Undefined, Null, Boolean, String, Number и Object.

Правильно:
Языковые типы соответствуют значениям, которыми непосредственно манипулирует создатель кода на языке ECMAScript. **К языковым типам относятся**: Undefined, Null, Boolean, String, Number и Object.

**Comment by iliakan** [comment]
Извините, этот стандарт устарел. Пожалуйста не надо его читать.

**Comment by demimurych** [comment]
Это единственный перевод который заслуживает внимания. 
Ничего лучше этого перевода нет в принципе. mdn и javascript.ru в том числе не заслуживают и десятой части внимания, которое должно быть у этого перевода. 

И, что еще хуже, и не предвидеться в будущем. 

Потому,  на мой взгляд, его ни в коем случае нельзя сдавать в архив. 
В этом переводе практически все верно, за исключением того что не хватает последних нововведений. 

Но, по крайней мере, тут есть прекрасно переведенная база языка.
